FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd curl && rm -rf /var/lib/apt/lists/*

COPY schema/ ./schema/
COPY init-kafka.sh ./init-kafka.sh

RUN chmod +x ./init-kafka.sh

CMD ["./init-kafka.sh"]
